# SPDX-License-Identifier: BSD-2-Clause

platform-objs-y += platform.o

PLATFORM_RISCV_XLEN = 32
PLATFORM_RISCV_ABI = ilp32
PLATFORM_RISCV_ISA = rv32imac_zicsr_zifencei
PLATFORM_RISCV_CODE_MODEL = medany

FW_DYNAMIC = n
FW_JUMP = n
FW_PAYLOAD = y
FW_PAYLOAD_OFFSET = 0x00400000
FW_PAYLOAD_FDT_OFFSET = 0x00200000
FW_PAYLOAD_ALIGN = 0x1000
