`include "../peripheral/gpio_mmio.sv"
`include "../peripheral/ddr3_wb_bridge.sv"
`include "../peripheral/i2c_mmio.sv"
`include "../peripheral/spi_mmio.sv"
`include "../peripheral/sdhost_mmio.sv"
`include "../peripheral/timer_mmio.sv"
`include "../peripheral/uart_mmio.sv"
`include "../peripheral/clint.sv"
